### ISSUE TITLE
Error in command npm start

### ISSUE THREAD

**Issue by ruchikam** [bravi-software/knextancy-example#1]
url.js:103
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at Object.<anonymous> (/home/ajay/Desktop/knextancy-example-master/config/env.js:11:15)
    at Module._compile (module.js:652:30)
    at loader (/home/ajay/Desktop/knextancy-example-master/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ajay/Desktop/knextancy-example-master/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/ajay/Desktop/knextancy-example-master/config/index.js:10:39
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/ajay/Desktop/knextancy-example-master/config/index.js:9:6)
    at Module._compile (module.js:652:30)
    at loader (/home/ajay/Desktop/knextancy-example-master/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ajay/Desktop/knextancy-example-master/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! knextancy-example@1.0.0 start: `node ./bin/service.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the knextancy-example@1.0.0 start script.

**Comment by krolow** [comment]
have u passed those env vars:

https://github.com/bravi-software/knextancy-example/blob/master/config/env.js#L10-L16

**Comment by ruchikam** [comment]
db: &DB
  image: postgres:9.4.4
  ports:
    - 5432
  environment:
    POSTGRES_USER: ctrmdvdfcrqljj
    POSTGRES_PASSWORD: db35345e3d63d318e372f360000fcf82669d465451c671550af4dbc0c88a1086
    POSTGRES_DB: d2pjluiq7l61ha

I had updated this in docker-compose.yml file
